version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/upstreams:/etc/nginx/upstreams
      - ./nginx/servers:/etc/nginx/servers
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./disable.sh:/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh